version: '3.8'

services:
  dinq_message:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: dinq_message
    env_file:
      - ../.env
    ports:
      - "80:8080"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - dinq_network

  redis:
    image: redis:7-alpine
    container_name: dinq_message_redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - dinq_network

networks:
  dinq_network:
    name: dinq_network
    driver: bridge

volumes:
  redis_data:
